[project]
name = "Automated-Market-Maker"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.automated-market-maker]
path = "contracts/automated-market-maker.clar"
depends_on = []

[contracts.ft-trait]
path = "contracts/ft-trait.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
